
  export class TransactionModel {
    id?:number
    uuid?:string
    reference?:string
    companyId?:number
    companyBankId?:number
    thirdId?:number
    thirdBankId?:number
    companyTeamId?:number
    quantity?:number
    averageValue?:string
    value?:string
    expirationDate?:Date
    observations?:string
    statusProcess?:string
    status?:string
    createdAt?:Date
    payedAt?:Date
    updatedAt?:Date
    deletedAt?:Date
    groupPayingId?:any
    constructor(
      {
        id,
        uuid,
        reference,
        companyId,
        companyBankId,
        thirdId,
        thirdBankId,
        companyTeamId,
        quantity,
        averageValue,
        value,
        expirationDate,
        observations,
        statusProcess,
        status,
        createdAt,
        payedAt,
        updatedAt,
        deletedAt,
        groupPayingId,
      }:{
        id?:number,
        uuid?:string,
        reference?:string,
        companyId?:number,
        companyBankId?:number,
        thirdId?:number,
        thirdBankId?:number,
        companyTeamId?:number,
        quantity?:number,
        averageValue?:string,
        value?:string,
        expirationDate?:Date,
        observations?:string,
        statusProcess?:string,
        status?:string,
        createdAt?:Date,
        payedAt?:Date,
        updatedAt?:Date,
        deletedAt?:Date,
        groupPayingId?:any,
      }
    ){
        this.id=id
        this.uuid=uuid
        this.reference=reference
        this.companyId=companyId
        this.companyBankId=companyBankId
        this.thirdId=thirdId
        this.thirdBankId=thirdBankId
        this.companyTeamId=companyTeamId
        this.quantity=quantity
        this.averageValue=averageValue
        this.value=value
        this.expirationDate=expirationDate
        this.observations=observations
        this.statusProcess=statusProcess
        this.status=status
        this.createdAt=createdAt
        this.payedAt=payedAt
        this.updatedAt=updatedAt
        this.deletedAt=deletedAt
        this.groupPayingId=groupPayingId
    }
};



