
  export class TeamModel {
    id?:number
    roleId?:number
    uuid?:string
    email?:string
    emailValidationCode?:string
    emailValidation?:boolean
    indicative?:string
    phone?:string
    phoneValidationCode?:string
    phoneValidation?:boolean
    password?:string
    photo?:string
    firstName?:string
    lastName?:string
    step?:number
    status?:string
    phoneOtp?:string
    createdAt?:Date
    updatedAt?:Date
    deletedAt?:Date
    constructor(
      {
        id,
        roleId,
        uuid,
        email,
        emailValidationCode,
        emailValidation,
        indicative,
        phone,
        phoneValidationCode,
        phoneValidation,
        password,
        photo,
        firstName,
        lastName,
        step,
        status,
        phoneOtp,
        createdAt,
        updatedAt,
        deletedAt,
      }:{
        id?:number,
        roleId?:number,
        uuid?:string,
        email?:string,
        emailValidationCode?:string,
        emailValidation?:boolean,
        indicative?:string,
        phone?:string,
        phoneValidationCode?:string,
        phoneValidation?:boolean,
        password?:string,
        photo?:string,
        firstName?:string,
        lastName?:string,
        step?:number,
        status?:string,
        phoneOtp?:string,
        createdAt?:Date,
        updatedAt?:Date,
        deletedAt?:Date,
      }
    ){
        this.id=id
        this.roleId=roleId
        this.uuid=uuid
        this.email=email
        this.emailValidationCode=emailValidationCode
        this.emailValidation=emailValidation
        this.indicative=indicative
        this.phone=phone
        this.phoneValidationCode=phoneValidationCode
        this.phoneValidation=phoneValidation
        this.password=password
        this.photo=photo
        this.firstName=firstName
        this.lastName=lastName
        this.step=step
        this.status=status
        this.phoneOtp=phoneOtp
        this.createdAt=createdAt
        this.updatedAt=updatedAt
        this.deletedAt=deletedAt
    }
};



